const styles = {
  wedding: {
    0: {
      boxStyle: {
        width: "1000px",
        height: "auto",
        border: "1px solid #e2e2e2",
        position: "relative",
        overflow: "hidden",
      },
      bgStyle: {
        width: "1000px",
        height: "auto",
        objectFit: "cover",
        position: "absolute",
        top: "0",
        left: "0",
      },
      bgPath:
        "https://res.cloudinary.com/ajinkyasarjeraoveer/image/upload/v1745235751/wedding/template/01_bdehck.png",
      cardPath:
        "https://res.cloudinary.com/ajinkyasarjeraoveer/image/upload/v1745235853/wedding/cards/01_yyneve.png",
      texts: [
        {
          name: ["P]ZjoF{"],
          identifier: "brideName",
          isKeyboardRequired: true,
          style: {
            top: "105px",
            left: "296px",
            color: "#83173f",
            fontSize: "85px",
            fontFamily: "cv-maya",
          },
        },
        {
          name: ["cIFo"],
          identifier: "groomName",
          isKeyboardRequired: true,
          style: {
            top: "192px",
            left: "315px",
            color: "#83173f",
            fontSize: "85px",
            fontFamily: "cv-maya",
          },
        },
        {
          name: ["चि.सौ.का."],
          identifier: "brideTag",
          style: {
            top: "117px",
            left: "408px",
            color: "#83173f",
            fontSize: "15px",
            fontFamily: "baloo",
          },
        },
        {
          name: ["चिरंजीव"],
          identifier: "groomTag",
          style: {
            top: "206px",
            left: "427px",
            color: "#83173f",
            fontSize: "15px",
            fontFamily: "baloo",
          },
        },
        {
          name: [
            "श्री. मधुकर शिवाजी सावंत",
            "यांची जेष्ठ कन्या",
            "मु.पो.वांगणी ता.वेल्हा जि.पुणे",
          ],
          identifier: "brideParent",
          style: {
            top: "129px",
            left: "493px",
            color: "#83173f",
            fontSize: "15px",
            fontFamily: "baloo",
          },
        },
        {
          name: [
            "श्री. अप्पासाहेब शिवाप्पा गायकवाड",
            "यांचे द्वितीय पुत्र",
            "मु.पो.वांगणी ता.वेल्हा जि.पुणे",
          ],
          identifier: "groomParent",
          style: {
            top: "221px",
            left: "492px",
            color: "#83173f",
            fontSize: "15px",
            fontFamily: "baloo",
          },
        },
        {
          name: [
            "रविवार दि. १४/०५/२०२५ रोजी",
            "दुपारी ४ वा. ३७ मि.",
            "या शुभमुहूर्तावर करण्याचे योजिले आहे",
          ],
          identifier: "weddingDateTime",
          style: {
            top: "446px",
            left: "393px",
            color: "#83173f",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: ["ज्ञान मंगल कार्यालय"],
          identifier: "weddingHall",
          style: {
            top: "580px",
            left: "404px",
            color: "#ffff8f",
            fontSize: "25px",
            fontFamily: "baloo",
            textAlign: "center",
            fontStyle: "bold",
          },
        },
        {
          name: [
            "पुणे - बँगलोर रोड, इंदोली फाटा,",
            "पेरले, ता. कराड, जि. सातारा",
          ],
          identifier: "weddingAdd",
          style: {
            top: "614px",
            left: "421px",
            color: "#fff",
            fontSize: "15px",
            fontFamily: "baloo",
            textAlign: "center",
            fontStyle: "itallic",
          },
        },
        {
          name: ["निमंत्रक : "],
          identifier: "invitorTag",
          style: {
            top: "743px",
            left: "258px",
            color: "#fff",
            fontSize: "30px",
            fontFamily: "hind",
            textAlign: "center",
          },
        },
        {
          name: ["समस्त सावंत परिवार"],
          identifier: "invitor",
          style: {
            top: "741px",
            left: "379px",
            color: "#ffff8f",
            fontSize: "35px",
            fontFamily: "hind",
            textAlign: "center",
          },
        },
      ],
    },
    1: {
      boxStyle: {
        width: "1000px",
        height: "auto",
        border: "1px solid #e2e2e2",
        position: "relative",
        overflow: "hidden",
      },
      bgStyle: {
        width: "1000px",
        height: "auto",
        objectFit: "cover",
        position: "absolute",
        top: "0",
        left: "0",
      },
      bgPath:
        "https://res.cloudinary.com/ajinkyasarjeraoveer/image/upload/v1745235750/wedding/template/02_l5x35t.png",
      cardPath:
        "https://res.cloudinary.com/ajinkyasarjeraoveer/image/upload/v1745235852/wedding/cards/02_mryqbu.png",
      texts: [
        {
          name: ["AaHaya"],
          identifier: "groomName",
          isKeyboardRequired: true,
          style: {
            top: "175px",
            left: "398px",
            color: "#6a2f29",
            fontSize: "100px",
            fontFamily: "dg-pro-03",
          },
        },
        {
          name: ["FeSvayaaQ"],
          identifier: "brideName",
          isKeyboardRequired: true,
          style: {
            top: "355px",
            left: "396px",
            color: "#6a2f29",
            fontSize: "100px",
            fontFamily: "dg-pro-03",
          },
        },
        {
          name: ["चि."],
          identifier: "groomTag",
          style: {
            top: "233px",
            left: "353px",
            color: "#9d4200",
            fontSize: "20px",
            fontFamily: "shreedev-0715",
          },
        },
        {
          name: ["चि.सौ.का."],
          identifier: "brideTag",
          style: {
            top: "417px",
            left: "306px",
            color: "#9d4200",
            fontSize: "20px",
            fontFamily: "shreedev-0715",
          },
        },
        {
          name: [
            "श्री. अप्पासाहेब शिवाप्पा गायकवाड ",
            "मु. पो. भाटेवाडी, सोलापूर यांचे कनिष्ठ सुपूत्र",
          ],
          identifier: "groomParent",
          style: {
            top: "300px",
            left: "366px",
            color: "#5e5e5e",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: [
            "श्री. मधुकर शिवाजी सावंत",
            "मु. पो. सावंतवाडी, पाटण यांची द्वितीय सुकन्या",
          ],
          identifier: "brideParent",
          style: {
            top: "476px",
            left: "358px",
            color: "#5e5e5e",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: [
            "रविवार दि. १४.१२.२०२५ रोजी सकाळी ११:४० मी. ",
            "या शुभमुहूर्तावर करण्याचे योजिले आहे",
          ],
          identifier: "weddingDateTime",
          style: {
            top: "720px",
            left: "285px",
            color: "#982026",
            fontSize: "22px",
            fontFamily: "poppins",
            textAlign: "center",
            fontStyle: "bold",
          },
        },
        {
          name: ["ज्ञान मंगल कार्यालय"],
          identifier: "weddingHall",
          style: {
            top: "830px",
            left: "427px",
            color: "#a90038",
            fontSize: "20px",
            fontFamily: "baloo",
            textAlign: "center",
            fontStyle: "bold",
          },
        },
        {
          name: ["पाचवड फाटा,", "ता. कराड जि. सातारा"],
          identifier: "weddingAdd",
          style: {
            top: "853px",
            left: "446px",
            color: "#616161",
            fontSize: "15px",
            fontFamily: "baloo",
            textAlign: "center",
            fontStyle: "itallic",
          },
        },
        {
          name: ["समस्त गायकवाड परिवार"],
          identifier: "invitor",
          style: {
            top: "958px",
            left: "363px",
            color: "#a90038",
            fontSize: "32px",
            fontFamily: "hind",
            textAlign: "center",
          },
        },
      ],
    },
    2: {
      boxStyle: {
        width: "1000px",
        height: "auto",
        border: "1px solid #e2e2e2",
        position: "relative",
        overflow: "hidden",
      },
      bgStyle: {
        width: "1000px",
        height: "auto",
        objectFit: "cover",
        position: "absolute",
        top: "0",
        left: "0",
      },
      bgPath:
        "https://res.cloudinary.com/ajinkyasarjeraoveer/image/upload/v1745235758/wedding/template/03_ovfqza.png",
      cardPath:
        "https://res.cloudinary.com/ajinkyasarjeraoveer/image/upload/v1745235858/wedding/cards/03_q51bon.png",
      texts: [
        {
          name: ["AaHaya"],
          identifier: "groomName",
          isKeyboardRequired: true,
          style: {
            top: "251px",
            left: "419px",
            color: "#6a2f29",
            fontSize: "80px",
            fontFamily: "dg-pro-03",
          },
        },
        {
          name: ["FeSvayaaQ"],
          identifier: "brideName",
          isKeyboardRequired: true,
          style: {
            top: "384px",
            left: "412px",
            color: "#6a2f29",
            fontSize: "80px",
            fontFamily: "dg-pro-03",
          },
        },
        {
          name: ["चि."],
          identifier: "groomTag",
          style: {
            top: "294px",
            left: "376px",
            color: "#9d4200",
            fontSize: "20px",
            fontFamily: "poppins",
          },
        },
        {
          name: ["चि.सौ.का."],
          identifier: "brideTag",
          style: {
            top: "428px",
            left: "310px",
            color: "#9d4200",
            fontSize: "20px",
            fontFamily: "poppins",
          },
        },
        {
          name: [
            "श्री. अप्पासाहेब शिवाप्पा गायकवाड ",
            "मु. पो. भाटेवाडी, सोलापूर यांचे कनिष्ठ सुपूत्र",
          ],
          identifier: "groomParent",
          style: {
            top: "347px",
            left: "365px",
            color: "#5e5e5e",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: [
            "श्री. मधुकर शिवाजी सावंत",
            "मु. पो. सावंतवाडी, पाटण यांची द्वितीय सुकन्या",
          ],
          identifier: "brideParent",
          style: {
            top: "476px",
            left: "358px",
            color: "#5e5e5e",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: [
            "रविवार दि. १४.१२.२०२५ रोजी सा. ०४:३५ मी. ",
            "या शुभमुहूर्तावर करण्याचे योजिले आहे",
          ],
          identifier: "weddingDateTime",
          style: {
            top: "622px",
            left: "330px",
            color: "#982026",
            fontSize: "18px",
            fontFamily: "poppins",
            textAlign: "center",
            fontStyle: "bold",
          },
        },
        {
          name: ["ज्ञान मंगल कार्यालय"],
          identifier: "weddingHall",
          style: {
            top: "778px",
            left: "436px",
            color: "#a90038",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
            fontStyle: "bold",
          },
        },
        {
          name: ["पाचवड फाटा, ता. कराड जि. सातारा"],
          identifier: "weddingAdd",
          style: {
            top: "802px",
            left: "414px",
            color: "#616161",
            fontSize: "14px",
            fontFamily: "baloo",
            textAlign: "center",
            fontStyle: "itallic",
          },
        },
        {
          name: ["रविवार दि. १४/१२/२०२५ रोजी", "सकाळी १०:३० रोजी विवाहस्थळी"],
          identifier: "engagementDetails",
          style: {
            top: "708px",
            left: "317px",
            color: "#5e5e5e",
            fontSize: "14px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: ["रविवार दि. १४/१२/२०२५ रोजी", "सकाळी ११:४५ रोजी विवाहस्थळी"],
          identifier: "haldiDetails",
          style: {
            top: "707px",
            left: "533px",
            color: "#5e5e5e",
            fontSize: "14px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: ["समस्त गायकवाड परिवार"],
          identifier: "invitor",
          style: {
            top: "864px",
            left: "372px",
            color: "#bf3900",
            fontSize: "28px",
            fontFamily: "hind",
            textAlign: "center",
          },
        },
      ],
    },
    3: {
      boxStyle: {
        width: "1000px",
        height: "auto",
        border: "1px solid #e2e2e2",
        position: "relative",
        overflow: "hidden",
      },
      bgStyle: {
        width: "1000px",
        height: "auto",
        objectFit: "cover",
        position: "absolute",
        top: "0",
        left: "0",
      },
      bgPath:
        "https://res.cloudinary.com/ajinkyasarjeraoveer/image/upload/v1745235748/wedding/template/04_de4li0.png",
      cardPath:
        "https://res.cloudinary.com/ajinkyasarjeraoveer/image/upload/v1745235868/wedding/cards/04_gstrls.png",
      texts: [
        {
          name: ["AHaya"],
          identifier: "groomName",
          isKeyboardRequired: true,
          style: {
            top: "290px",
            left: "365px",
            color: "#db8f14",
            fontSize: "100px",
            fontFamily: "sau-97",
          },
        },
        {
          name: ["FeSvayaaQ"],
          identifier: "brideName",
          isKeyboardRequired: true,
          style: {
            top: "513px",
            left: "365px",
            color: "#db8f14",
            fontSize: "100px",
            fontFamily: "sau-97",
          },
        },
        {
          name: ["चि."],
          identifier: "groomTag",
          style: {
            top: "300px",
            left: "569px",
            color: "#97590e",
            fontSize: "25px",
            fontFamily: "poppins",
          },
        },
        {
          name: ["चि.सौ.का."],
          identifier: "brideTag",
          style: {
            top: "521px",
            left: "465px",
            color: "#97590e",
            fontSize: "25px",
            fontFamily: "poppins",
          },
        },
        {
          name: [
            "श्री. अप्पासाहेब शिवाप्पा गायकवाड ",
            "मु. पो. भाटेवाडी, सोलापूर यांचे कनिष्ठ सुपूत्र",
          ],
          identifier: "groomParent",
          style: {
            top: "442px",
            left: "365px",
            color: "#97590e",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: [
            "श्री. मधुकर शिवाजी सावंत",
            "मु. पो. सावंतवाडी, पाटण यांची द्वितीय सुकन्या",
          ],
          identifier: "brideParent",
          style: {
            top: "660px",
            left: "365px",
            color: "#97590e",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: ["रविवार दि. १४.१२.२०२५ रोजी", "सकाळी ११:४० मी."],
          identifier: "weddingDateTime",
          style: {
            top: "965px",
            left: "411px",
            color: "#97590e",
            fontSize: "15px",
            fontFamily: "poppins",
            textAlign: "center",
          },
        },
        {
          name: ["ज्ञान मंगल कार्यालय"],
          identifier: "weddingHall",
          style: {
            top: "1077px",
            left: "431px",
            color: "#97590e",
            fontSize: "20px",
            fontFamily: "baloo",
            textAlign: "center",
            fontStyle: "bold",
          },
        },
        {
          name: ["पाचवड फाटा, ता. कराड जि. सातारा"],
          identifier: "weddingAdd",
          style: {
            top: "1107px",
            left: "412px",
            color: "#97590e",
            fontSize: "15px",
            fontFamily: "baloo",
            textAlign: "center",
            fontStyle: "itallic",
          },
        },
        {
          name: ["समस्त गायकवाड परिवार"],
          identifier: "invitor",
          style: {
            top: "1186px",
            left: "353px",
            color: "#97590e",
            fontSize: "32px",
            fontFamily: "hind",
            textAlign: "center",
          },
        },
      ],
    },
    4: {
      boxStyle: {
        width: "1000px",
        height: "auto",
        border: "1px solid #e2e2e2",
        position: "relative",
        overflow: "hidden",
      },
      bgStyle: {
        width: "1000px",
        height: "auto",
        objectFit: "cover",
        position: "absolute",
        top: "0",
        left: "0",
      },
      bgPath:
        "https://res.cloudinary.com/ajinkyasarjeraoveer/image/upload/v1745235754/wedding/template/05_ywjiot.png",
      cardPath:
        "https://res.cloudinary.com/ajinkyasarjeraoveer/image/upload/v1745235876/wedding/cards/05_pmpjnd.png",
      texts: [
        {
          name: ["ĒaƮ{ųa"],
          identifier: "groomName",
          isKeyboardRequired: true,
          style: {
            top: "334px",
            left: "284px",
            color: "#7b2a05",
            fontSize: "85px",
            fontFamily: "dgcally-10",
          },
        },
        {
          name: ["ĨȠSvayaǽȭ"],
          identifier: "brideName",
          isKeyboardRequired: true,
          style: {
            top: "431px",
            left: "237px",
            color: "#7b2a05",
            fontSize: "85px",
            fontFamily: "dgcally-10",
          },
        },
        {
          name: ["चि."],
          identifier: "groomTag",
          style: {
            top: "351px",
            left: "352px",
            color: "#9c5001",
            fontSize: "15px",
            fontFamily: "poppins",
          },
        },
        {
          name: ["चि.सौ.का."],
          identifier: "brideTag",
          style: {
            top: "447px",
            left: "305px",
            color: "#9c5001",
            fontSize: "15px",
            fontFamily: "poppins",
          },
        },
        {
          name: [
            "श्री. अप्पासाहेब शिवाप्पा गायकवाड ",
            "मु. पो. भाटेवाडी, सोलापूर यांचे कनिष्ठ सुपूत्र",
          ],
          identifier: "groomParent",
          style: {
            top: "371px",
            left: "513px",
            color: "#6d2711",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: [
            "श्री. मधुकर शिवाजी सावंत",
            "मु. पो. सावंतवाडी, पाटण यांची द्वितीय सुकन्या",
          ],
          identifier: "brideParent",
          style: {
            top: "455px",
            left: "503px",
            color: "#6d2711",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: [
            "रविवार दि. १४.१२.२०२५ रोजी सा. ०४:३५ मी. ",
            "या शुभमुहूर्तावर करण्याचे योजिले आहे",
          ],
          identifier: "weddingDateTime",
          style: {
            top: "686px",
            left: "383px",
            color: "#6d2711",
            fontSize: "13px",
            fontFamily: "poppins",
            textAlign: "center",
            fontStyle: "bold",
          },
        },
        {
          name: ["ज्ञान मंगल कार्यालय"],
          identifier: "weddingHall",
          style: {
            top: "799px",
            left: "425px",
            color: "#fff",
            fontSize: "25px",
            fontFamily: "khand",
            textAlign: "center",
            fontStyle: "bold",
          },
        },
        {
          name: ["पाचवड फाटा, ता. कराड जि. सातारा"],
          identifier: "weddingAdd",
          style: {
            top: "833px",
            left: "421px",
            color: "#fff",
            fontSize: "14px",
            fontFamily: "baloo",
            textAlign: "center",
            fontStyle: "itallic",
          },
        },
        {
          name: ["रविवार दि. १४/१२/२०२५ रोजी", "सकाळी १०:३० रोजी विवाहस्थळी"],
          identifier: "engagementDetails",
          style: {
            top: "948px",
            left: "266px",
            color: "#7b2a05",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: ["रविवार दि. १४/१२/२०२५ रोजी", "सकाळी ११:४५ रोजी विवाहस्थळी"],
          identifier: "haldiDetails",
          style: {
            top: "948px",
            left: "531px",
            color: "#7b2a05",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: ["समस्त गायकवाड परिवार"],
          identifier: "invitor",
          style: {
            top: "1070px",
            left: "378px",
            color: "#7b2a05",
            fontSize: "28px",
            fontFamily: "hind",
            textAlign: "center",
          },
        },
      ],
    },
    5: {
      boxStyle: {
        width: "1000px",
        height: "auto",
        border: "1px solid #e2e2e2",
        position: "relative",
        overflow: "hidden",
      },
      bgStyle: {
        width: "1000px",
        height: "auto",
        objectFit: "cover",
        position: "absolute",
        top: "0",
        left: "0",
      },
      bgPath:
        "https://res.cloudinary.com/ajinkyasarjeraoveer/image/upload/v1745322200/wedding/template/5_o8w41z.png",
      cardPath:
        "https://res.cloudinary.com/ajinkyasarjeraoveer/image/upload/v1745322154/wedding/cards/5_borpel.png",
      texts: [
        {
          name: ["AHaya"],
          identifier: "groomName",
          isKeyboardRequired: true,
          style: {
            top: "72px",
            left: "140px",
            color: "#6a1904",
            fontSize: "85px",
            fontFamily: "sau-49",
          },
        },
        {
          name: ["FeSvayaaQ"],
          identifier: "brideName",
          isKeyboardRequired: true,
          style: {
            top: "72px",
            left: "659px",
            color: "#6a1904",
            fontSize: "85px",
            fontFamily: "sau-49",
          },
        },
        {
          name: ["चि."],
          identifier: "groomTag",
          style: {
            top: "78px",
            left: "201px",
            color: "#cd411b",
            fontSize: "15px",
            fontFamily: "poppins",
          },
        },
        {
          name: ["चि.सौ.का."],
          identifier: "brideTag",
          style: {
            top: "75px",
            left: "704px",
            color: "#cd411b",
            fontSize: "15px",
            fontFamily: "poppins",
          },
        },
        {
          name: [
            "श्री. अप्पासाहेब शिवाप्पा गायकवाड ",
            "मु. पो. भाटेवाडी, सोलापूर यांचे कनिष्ठ सुपूत्र",
          ],
          identifier: "groomParent",
          style: {
            top: "188px",
            left: "117px",
            color: "#cd411b",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: [
            "श्री. मधुकर शिवाजी सावंत",
            "मु. पो. सावंतवाडी, पाटण यांची द्वितीय सुकन्या",
          ],
          identifier: "brideParent",
          style: {
            top: "188px",
            left: "652px",
            color: "#cd411b",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: [
            "रविवार दि. १४.१२.२०२५ रोजी सा. ०४:३५ मी. ",
            "या शुभमुहूर्तावर करण्याचे योजिले आहे",
          ],
          identifier: "weddingDateTime",
          style: {
            top: "480px",
            left: "378px",
            color: "#cd411b",
            fontSize: "20px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: ["ज्ञान मंगल कार्यालय"],
          identifier: "weddingHall",
          style: {
            top: "600px",
            left: "386px",
            color: "#981c12",
            fontSize: "25px",
            fontFamily: "poppins",
            textAlign: "center",
          },
        },
        {
          name: ["पाचवड फाटा, ता. कराड जि. सातारा"],
          identifier: "weddingAdd",
          style: {
            top: "636px",
            left: "391px",
            color: "#981c12",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
            fontStyle: "itallic",
          },
        },
        {
          name: [
            "श्री. रामचंद्र निवृत्ती गायकवाड",
            "श्री. श्रीपती निवृत्ती गायकवाड",
            "श्री. लक्ष्मण निवृत्ती गायकवाड",
          ],
          identifier: "invitor",
          style: {
            top: "721px",
            left: "383px",
            color: "#b6360c",
            fontSize: "20px",
            fontFamily: "hind",
            textAlign: "center",
          },
        },
      ],
    },
    6: {
      boxStyle: {
        width: "1000px",
        height: "auto",
        border: "1px solid #e2e2e2",
        position: "relative",
        overflow: "hidden",
      },
      bgStyle: {
        width: "1000px",
        height: "auto",
        objectFit: "cover",
        position: "absolute",
        top: "0",
        left: "0",
      },
      bgPath:
        "https://res.cloudinary.com/ajinkyasarjeraoveer/image/upload/v1745322189/wedding/template/6_o5tgec.png",
      cardPath:
        "https://res.cloudinary.com/ajinkyasarjeraoveer/image/upload/v1745322154/wedding/cards/6_u5vb7i.png",
      texts: [
        {
          name: ["अक्षय"],
          identifier: "groomName",
          style: {
            top: "142px",
            left: "165px",
            backgroundImage:
              "linear-gradient(to bottom, #f35e1b 0%, #b30c15 100%)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            fontSize: "120px",
            fontFamily: "tillana-bold",
          },
        },
        {
          name: ["ऐश्वर्या"],
          identifier: "brideName",
          style: {
            top: "348px",
            left: "190px",
            backgroundImage:
              "linear-gradient(to bottom, #f35e1b 0%, #b30c15 100%)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            fontSize: "120px",
            fontFamily: "tillana-bold",
          },
        },
        {
          name: ["चि."],
          identifier: "groomTag",
          style: {
            top: "192px",
            left: "145px",
            color: "#990041",
            fontSize: "18px",
            fontFamily: "baloo",
          },
        },
        {
          name: ["चि.", "सौ.", "का."],
          identifier: "brideTag",
          style: {
            top: "396px",
            left: "160px",
            color: "#990041",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: [
            "श्री. अप्पासाहेब शिवाप्पा गायकवाड ",
            "मु. पो. भाटेवाडी, सोलापूर यांचे कनिष्ठ सुपूत्र",
          ],
          identifier: "groomParent",
          style: {
            top: "133px",
            left: "359px",
            color: "#990041",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: [
            "श्री. मधुकर शिवाजी सावंत",
            "मु. पो. सावंतवाडी, पाटण यांची द्वितीय सुकन्या",
          ],
          identifier: "brideParent",
          style: {
            top: "303px",
            left: "359px",
            color: "#990041",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: [
            "रविवार दि. १४.१२.२०२५ रोजी सा. ०४:३५ मी. ",
            "या शुभमुहूर्तावर करण्याचे योजिले आहे",
          ],
          identifier: "weddingDateTime",
          style: {
            top: "857px",
            left: "346px",
            color: "#990041",
            fontSize: "20px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: ["ज्ञान मंगल कार्यालय"],
          identifier: "weddingHall",
          style: {
            top: "998px",
            left: "388px",
            color: "#7c4407",
            fontSize: "25px",
            fontFamily: "poppins",
            textAlign: "center",
          },
        },
        {
          name: ["पाचवड फाटा, ता. कराड जि. सातारा"],
          identifier: "weddingAdd",
          style: {
            top: "1034px",
            left: "395px",
            color: "#a35603",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
            fontStyle: "itallic",
          },
        },
        {
          name: [
            "श्री. रामचंद्र निवृत्ती गायकवाड",
            "श्री. श्रीपती निवृत्ती गायकवाड",
            "श्री. लक्ष्मण निवृत्ती गायकवाड",
          ],
          identifier: "invitor",
          style: {
            top: "1126px",
            left: "390px",
            color: "#b6360c",
            fontSize: "20px",
            fontFamily: "hind",
            textAlign: "center",
          },
        },
      ],
    },
    7: {
      boxStyle: {
        width: "1000px",
        height: "auto",
        border: "1px solid #e2e2e2",
        position: "relative",
        overflow: "hidden",
      },
      bgStyle: {
        width: "1000px",
        height: "auto",
        objectFit: "cover",
        position: "absolute",
        top: "0",
        left: "0",
      },
      bgPath:
        "https://res.cloudinary.com/ajinkyasarjeraoveer/image/upload/v1745322192/wedding/template/7_gg75fc.png",
      cardPath:
        "https://res.cloudinary.com/ajinkyasarjeraoveer/image/upload/v1745322154/wedding/cards/7_menzqw.png",
      texts: [
        {
          name: ["अक्षय"],
          identifier: "groomName",
          style: {
            top: "222px",
            left: "413px",
            backgroundImage:
              "linear-gradient(to bottom, #831343 0%, #ff368c 100%)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            fontSize: "100px",
            fontFamily: "khand",
          },
        },
        {
          name: ["ऐश्वर्या"],
          identifier: "brideName",
          style: {
            top: "412px",
            left: "409px",
            backgroundImage:
              "linear-gradient(to bottom, #831343 0%, #ff368c 100%)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            fontSize: "100px",
            fontFamily: "khand",
          },
        },
        {
          name: ["चि."],
          identifier: "groomTag",
          style: {
            top: "253px",
            left: "382px",
            color: "#990041",
            fontSize: "18px",
            fontFamily: "baloo",
          },
        },
        {
          name: ["चि.सौ.का."],
          identifier: "brideTag",
          style: {
            top: "441px",
            left: "341px",
            color: "#990041",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: [
            "श्री. अप्पासाहेब शिवाप्पा गायकवाड ",
            "मु. पो. भाटेवाडी, सोलापूर यांचे कनिष्ठ सुपूत्र",
          ],
          identifier: "groomParent",
          style: {
            top: "344px",
            left: "376px",
            color: "#990041",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: [
            "श्री. मधुकर शिवाजी सावंत",
            "मु. पो. सावंतवाडी, पाटण यांची द्वितीय सुकन्या",
          ],
          identifier: "brideParent",
          style: {
            top: "529px",
            left: "361px",
            color: "#990041",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: [
            "रविवार दि. १४.१२.२०२५ रोजी सा. ०४:३५ मी. ",
            "या शुभमुहूर्तावर करण्याचे योजिले आहे",
          ],
          identifier: "weddingDateTime",
          style: {
            top: "810px",
            left: "362px",
            color: "#990041",
            fontSize: "20px",
            fontFamily: "baloo",
            textAlign: "center",
          },
        },
        {
          name: ["ज्ञान मंगल कार्यालय"],
          identifier: "weddingHall",
          style: {
            top: "927px",
            left: "388px",
            color: "#831343",
            fontSize: "25px",
            fontFamily: "poppins",
            textAlign: "center",
          },
        },
        {
          name: ["पाचवड फाटा, ता. कराड जि. सातारा"],
          identifier: "weddingAdd",
          style: {
            top: "959px",
            left: "393px",
            color: "#990041",
            fontSize: "18px",
            fontFamily: "baloo",
            textAlign: "center",
            fontStyle: "itallic",
          },
        },
        {
          name: ["समस्त गायकवाड परिवार"],
          identifier: "invitor",
          style: {
            top: "1038px",
            left: "394px",
            color: "#831343",
            fontSize: "25px",
            fontFamily: "hind",
            textAlign: "center",
          },
        },
      ],
    },
  },
};

export default styles;
